CREATE DATABASE TTN_QL_KhachSan
DROP DATABASE TTN_QL_KhachSan
USE TTN_QL_KhachSan
GO
CREATE TABLE KHACHANG(
	MaKH INT PRIMARY KEY IDENTITY(1,1),
	HoTen NVARCHAR(100),
	GioiTinh BIT,
	SDT VARCHAR(50),
	DiaChi NVARCHAR(100),
	SoCMND VARCHAR(15)
);

CREATE TABLE NHANVIEN(
	MaNV INT PRIMARY KEY IDENTITY(1,1),
	TenNV NVARCHAR(100),
	NgaySinh DATE,
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	SDT VARCHAR(50),
	Luong INT,
	TaiKhoan VARCHAR(50),
	MatKhau VARCHAR(50),
	Quyen INT 
);

CREATE TABLE DICHVU(
	MaDV INT PRIMARY KEY IDENTITY(1,1),
	TenDV NVARCHAR(100),
	DonGia INT
);

CREATE TABLE DODUNG(
	MaDD INT PRIMARY KEY IDENTITY(1,1),
	TenDD NVARCHAR(100),
);

CREATE TABLE PHONG(
	MaP INT PRIMARY KEY IDENTITY(1,1),
	TenP NVARCHAR(100),
	DonGiaPhong INT,
    TrangThai NVARCHAR(50)
);

CREATE TABLE CHITIETPHONG(
	MaP INT,
	MaDD INT,
	SoLuongDD INT,
    FOREIGN KEY(MaP) REFERENCES dbo.PHONG,
	FOREIGN KEY(MaDD) REFERENCES dbo.DODUNG,

);

CREATE TABLE HOADON(
	MaHD int PRIMARY KEY IDENTITY(1,1),
	MaNV INT,
	MaKH INT,
	NgayVao DATE,
	NgayDi DATE,
	TongTien INT,
	TongTienDV INT,
	TongTienPhong INT,
	FOREIGN KEY(MaNV) REFERENCES dbo.NHANVIEN,
	FOREIGN KEY(MaKH) REFERENCES dbo.KHACHANG
);

CREATE TABLE KHACHHANG_PHONG(
	MaKH INT,
	MaP INT,
	FOREIGN KEY(MaKH) REFERENCES dbo.KHACHANG,
	FOREIGN KEY(MaP) REFERENCES dbo.PHONG
);

CREATE TABLE KHACHHANG_DICHVU(
	MaKH INT,
	MaDV INT,
	SoLuong INT,
	FOREIGN KEY(MaKH) REFERENCES dbo.KHACHANG,
	FOREIGN KEY(MaDV) REFERENCES dbo.DICHVU
)

